apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: {{ .Values.fastapi.service.type }}
  ports:
  - port: {{ .Values.fastapi.service.port }}
    targetPort: 8000
  selector:
    app: fastapi-backend
