{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-serviceaccount
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
