apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: {{ .Values.streamlit.service.type }}
  ports:
  - port: {{ .Values.streamlit.service.port }}
    targetPort: 8501
  selector:
    app: streamlit-frontend


